markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: page/:num

blog:
    name: 毒不懂你                                               # 博客名称
    description: 像梦一样回忆过去                                         # 博客描述
    title: 像梦一样回忆过去                                              # 网页标题
    url: /                                                # 博客地址
    duoshuo: dbdn                                            # 多说ID
    tongji:  ec415fe29a87863987f9b9b9dd866164                                            # 百度统计ID
    qiniu:                                               # 七牛云地址
author:
    name:  dbdn                                              # 作者名称
    email: hailang_hu@qq.com                                              # 邮箱地址
    weibo:                                               # 微博地址
    github: https://github.com/dbdn                                             # GitHub地址
    #logo:  https://avatars3.githubusercontent.com/u/12525800?v=3&s=460                                               # logo地址
    logo:  /res/img/avatar.jpg                                               # logo地址
    douban:
        name:                                            # 豆瓣地址名称
        key:                                             # 豆瓣API Key
